/// Flutter icons JokenpoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JokenpoIcons
///      fonts:
///       - asset: fonts/JokenpoIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class JokenpoIcons {
  JokenpoIcons._();

  static const _kFontFam = 'JokenpoIcons';
  static const _kFontPkg = null;

  static const IconData hand_rock = IconData(0xf255, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_paper = IconData(0xf256, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_scissors = IconData(0xf257, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
